### Получить продукт по productId
GET http://localhost:8080/product-service/products/one?productId=1

### Получить список продуктов по userId
GET http://localhost:8080/product-service/products/all?userId=1