spring:
  application:
    name: product-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/java_pro
    username: postgres
    password: password

server:
  servlet:
    context-path: "/product-service"

logging:
  level:
    root: info
